### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ak0327** [habvi/42_minishell#17]
# Subject specifications
## builtin
- [x] echo #58 
- [x] cd #178 
  - [x] basic cd
  - [x] CDPATH
  - [x] symlink
- [x] pwd #163 
- [x] environment variables #149 
  - [x] implement hash table #122
  - [x] implement env list
  - [x] env (display)
  - [x] export (sort & display, set)
  - [x] unset (delete)
- [x] exit #63 

## signal
- [x] prompt (empty or after wrote some stuff)
  - [x] SIGINT `^C`
  - [x] EOF `^D`
  - [x] SIGQUIT `^\`
- [x] running blocking command
  - [x] SIGINT `^C`
  - [x] EOF `^D`
  - [x] SIGQUIT `^\`
- [x] running here-document
  - [x] SIGINT `^C`
  - [x] EOF `^D`
  - [x] SIGQUIT `^\`

## redirect
- [x] redirect in `<`
- [x] here document `<<`
- [x] redirect out; overwrite  `>`
- [x] redirect out; append `>>`

## others
- [x] history
- [ ] expand environment variables
  - [x] expand var
  - [x] word splitting
    - [x] general
    - [ ] assignment
  - [x] del null token
- [x] `$?`
- [x] command execution
  - [x] multiple pipe `|` #44 
  - [x] search path
  - [x] envp
- [x] error message
- [x] abort

## bonus
- [x] and `&&`
- [x] or `||`
- [x] subshell `( )`
- [x] wildcard `*` in current

<br>

7月スケジュール🔥
- [x] 02: cd
- [x] 03: bnf, tokenizer
- [x] 04: parser, &&, ||, () 
- [x] 05: parser, &&, ||, () 
- [x] 06: heredoc
- [x] 07: command execution, envp, CDPATH
- [x] 08: expansion
- [x] 09: *, redirect, heredoc expansion
- [x] 10: signal (prompt, command, heredoc)
- [x] 11: error msg, status
- [x] 12: test, fix
- [x] 13: submit⭐

**Comment by ak0327** [comment]
チェック項目が多いので作業担当ごとに分割するのが良さそう

**Comment by ak0327** [comment]
良い感じに実装項目ごとにチェックボックスがあるので進捗管理に使えそう...！
titleを`test.py` から `TODO` に変更してみました。
やることたくさん...🥹
